p3 generateZstack.py mystery z_scaled_emissions_file/Z_constrained_tomograms/mystery.csv 100
p3 generateZstack.py multi_level z_scaled_emissions_file/Z_constrained_tomograms/multi_level_lead.csv 100
p3 generateZstack.py brick_gap z_scaled_emissions_file/Z_constrained_tomograms/brick_gap.csv 100
p3 generateZstack.py brick_no_gap z_scaled_emissions_file/Z_constrained_tomograms/brick_no_gap.csv 100
